# Generated by Django 4.2.1 on 2023-12-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='equipment_level',
            field=models.IntegerField(choices=[(1, 'Ножи, дубинки и скрытое огнестрельное оружие'), (2, 'Пистолеты, кастеты и компактные пистолеты-пулеметы'), (3, 'Полуавтоматические винтовки, топоры и дымовые гранаты'), (4, 'Снайперские винтовки, широкие клинки и метательные ножи'), (5, 'Штурмовые винтовки, бронебойные дротики и дробовики'), (6, 'Специальные винтовки с подавлением звука, ядовитые стрелы и технологически продвинутые маскировочные устройства')], default=1),
        ),
        migrations.AddField(
            model_name='agent',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.BooleanField(choices=[(0, 'Мертв'), (1, 'Жив')], default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='exp',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='client',
            name='killed_by',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agent'),
        ),
        migrations.AddField(
            model_name='client',
            name='price',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='client',
            name='security_level',
            field=models.IntegerField(choices=[(1, 'Цель с минимальной охраной, неосведомлена о возможной опасности'), (2, 'Цель, которая может иметь небольшую охрану, но её легко обойти'), (3, 'Цель, защищена опытной охраной и базовыми техническими средствами'), (4, 'Цель с высокой степенью защиты, включая физическую, электронную и техническую безопасность'), (5, 'Цель, охраняемая профессиональными телохранителями, современными системами безопасности и тщательной разведкой'), (6, 'Высокопоставленная личность, государственного значения, с максимальной защитой, включая военные силы, секретные службы и высокотехнологичные системы безопасности')], default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(choices=[(0, 'Мертв'), (1, 'Жив')], default=1),
        ),
        migrations.AlterField(
            model_name='agent',
            name='membership',
            field=models.BooleanField(choices=[(0, 'Исключен'), (1, 'Состоит в организации')], default=1),
        ),
    ]
