# Generated by Django 4.2.1 on 2023-12-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_equipment_level_agent_exp_agent_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='killed_by',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agent'),
        ),
    ]
