# Generated by Django 4.2.1 on 2023-12-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_client_killed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='death_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
