# Generated by Django 4.2.1 on 2023-12-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_client_death_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='nickname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='agent',
            name='equipment_level',
            field=models.IntegerField(choices=[(1, 'ножи, дубинки и скрытое огнестрельное оружие'), (2, 'пистолеты, кастеты и компактные пистолеты-пулеметы'), (3, 'полуавтоматические винтовки, топоры и дымовые гранаты'), (4, 'снайперские винтовки, широкие клинки и метательные ножи'), (5, 'штурмовые винтовки, бронебойные дротики и дробовики'), (6, 'специальные винтовки с подавлением звука, ядовитые стрелы и технологически продвинутые маскировочные устройства')], default=1),
        ),
        migrations.AlterField(
            model_name='agent',
            name='membership',
            field=models.BooleanField(choices=[(0, 'исключен'), (1, 'состоит в организации')], default=1),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.BooleanField(choices=[(0, 'мертв'), (1, 'жив')], default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='security_level',
            field=models.IntegerField(choices=[(1, 'цель с минимальной охраной, неосведомлена о возможной опасности'), (2, 'цель, которая может иметь небольшую охрану, но её легко обойти'), (3, 'цель, защищена опытной охраной и базовыми техническими средствами'), (4, 'цель с высокой степенью защиты, включая физическую, электронную и техническую безопасность'), (5, 'цель, охраняемая профессиональными телохранителями, современными системами безопасности и тщательной разведкой'), (6, 'высокопоставленная личность, государственного значения, с максимальной защитой, включая военные силы, секретные службы и высокотехнологичные системы безопасности')], default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(choices=[(0, 'мертв'), (1, 'жив')], default=1),
        ),
    ]
