# Generated by Django 4.2.1 on 2023-12-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_nickname_alter_agent_equipment_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
