# Generated by Django 4.2.1 on 2023-12-13 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_agent_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='death_time',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'успех'), (1, 'провал')], default=0)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agent')),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.client')),
            ],
        ),
    ]
