# Generated by Django 4.2.1 on 2023-12-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_remove_client_death_time_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='killed_by',
        ),
    ]
