# Generated by Django 4.2.1 on 2023-12-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_remove_client_killed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'успех'), (0, 'провал')], default=1),
        ),
    ]
