# Generated by Django 4.2.1 on 2023-12-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_eventforagents_eventforclients_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventforclients',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='eventforclients',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agents.client'),
        ),
    ]
