# Generated by Django 4.2.1 on 2023-12-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('membership', models.BooleanField(default=True)),
                ('start_membership', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
